### PR TITLE
added no auto commands ( noa ) before write

### PR DESCRIPTION
**Pull request by alexzanderr**
im using `trim.nvim` and i guess many people are using too. that plugin just trims trailing white space after buffer save, it has an autocmd attached.

when using both plugins at the same time, you cant write in insert mode because while you are writing the whitespace (space between the last word and current word) will be deleted.

so i added this minor change and made a PR.

its working, i've tested.

im making a PR into 'dev' branch to make sure nothing will break and to not destroy `main` branch. if its working, then you will merge on your own.

peace!

### CODE REVIEW

**Comment by Pocco81** [comment]
Nice feat! But won't this conflict with other plugins?

**Comment by alexzanderr** [comment]
well. yeah. other plugins that are attaching autocmds to the buffer save command. but they arent so many

the most used that have something relate to buffer modification or buffer save i know are:
- trim.nvim (my PR is especially for this one)
- formatter.nvim (this, from what i know, doesnt conflict because has a separate command)

personally, i have 102 plugins in my neovim config, i think i got them all (the ones made in lua) and there are no conflicts.

ofc, my config is not like everyone's. many people may have some autocommands attached to buffer write. like formatters. my personally i dont format after save, but other people may do.

so i will just leave it as it is for now, i think the solution would be to add a `config` in setup function (like `noa = true/false`), a little bit of docs and apply noa before write `if noa == true` or not.

**Comment by alexzanderr** [comment]
yeah. im gonna write some code and make another PR for this.

or can i edit the commit for this PR? (sorry, im new to PRs)

**Comment by Pocco81** [comment]
> or can i edit the commit for this PR? (sorry, im new to PRs)

yep you can can.

**Comment by Pocco81** [comment]
Heya! please check #33 :tada:

**Pull request closed without merging**
